### ISSUE TITLE
Possible bug in orient2d

### ISSUE THREAD

**Issue by rowanwins** [mourner/robust-predicates#2]
I'm not sure if this is a bug in concaveman or robust-predicates but I'm getting different results when trying to replace robust-orientation with this library (see [rationale](https://github.com/mapbox/concaveman/issues/16)).

I've published a [runkit here](https://runkit.com/rowanwins/robust-predicates) or the same thing is inline below

````
const rpOrient = require('robust-predicates/umd/orient2d.min.js').orient2d;

const orient = require("robust-orientation")

function intersects(p1, q1, p2, q2) {
    return p1 !== q2 && q1 !== p2 &&
        orient(p1, q1, p2) > 0 !== orient(p1, q1, q2) > 0 &&
        orient(p2, q2, p1) > 0 !== orient(p2, q2, q1) > 0;
}

function intersectsWithRp(p1, q1, p2, q2) {
    return p1 !== q2 && q1 !== p2 &&
        rpOrient(p1, q1, p2) > 0 !== rpOrient(p1, q1, q2) > 0 &&
        rpOrient(p2, q2, p1) > 0 !== rpOrient(p2, q2, q1) > 0;
}


const edge1 = [[-122.0607, 37.3849], [-122.0610, 37.3841]]

const edge2 = [[-122.0607, 37.3847], [-122.0607, 37.3848]]

console.log('with robust-orientation', intersects(edge1[0], edge2[0], edge1[1], edge2[1]))
// => with robust-orientation, true

console.log('with robust-predicates', intersectsWithRp(edge1[0], edge2[0], edge1[1], edge2[1]))
// => with robust-predicates, false
````

If was to hazard a guess I'd say it's something to do with appearance of `-122.0607` three times, indicating one edge is vertical. Here is a pic of the edges being tested
![scenario](https://user-images.githubusercontent.com/6735870/81875946-d9e4ca80-95c4-11ea-815d-f91e1364c381.jpg)

I'm not the best at maths so I though I'd submit for consideration so whether this is an issue with robust predicates or the edge intersection function, not sure :)

Hope the narrow test case helps 
Cheers
Rowan

**Comment by mourner** [comment]
@rowanwins one thing I noticed is that in the example above, you use `robust-predicates` with an incorrect signature — it differs in the way `x, y` are passed as numbers in the arguments, instead of an `{x, y}` object. So you need to pass 6 arguments to `orient2d` instead of 3 like in `robust-orientation`. Maybe that's where the issue stems from. Let me know if it's not.

**Comment by rowanwins** [comment]
Urgh facepalm - of course, ignore me!
